name: Kuvaj Keenetic FIP
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Skupljanje koda
        uses: actions/checkout@v4
        with:
          repository: hanwckf/bl-mt798x

      - name: Instalacija alata
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu device-tree-compiler git python3

      - name: Kompajliranje
        run: |
          chmod +x build.sh
          # Koristimo postojecu proverenu plocu sa istim procesorom i DDR4 memorijom:
          SOC=mt7981 BOARD=cmcc_rax3000m ./build.sh

      - name: Slanje gotovog FIP fajla
        uses: actions/upload-artifact@v4
        with:
          name: Keenetic-Hero-DDR4-FIP
          path: output/*
